"""
Export Handler
Handles exporting conversations and documents to various formats
"""

import json
from datetime import datetime
from typing import List, Dict, Optional


class ExportHandler:
    """
    Exports conversations and analysis to multiple formats
    """
    
    def __init__(self):
        pass
    
    def export_to_markdown(self, conversation: List[Dict], document_info: Dict = None) -> str:
        """
        Export conversation to Markdown format
        
        Args:
            conversation: List of message dicts with 'role' and 'content'
            document_info: Optional document metadata
        
        Returns:
            Formatted markdown string
        """
        md = []
        
        # Header
        md.append("# PDF Research Assistant - Conversation Export\n")
        md.append(f"**Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        
        if document_info:
            md.append("## Document Information\n")
            md.append(f"- **Filename:** {document_info.get('filename', 'Unknown')}")
            md.append(f"- **Upload Date:** {document_info.get('upload_date', 'Unknown')}")
            md.append(f"- **Size:** {document_info.get('size_mb', 0):.2f} MB")
            md.append("")
        
        md.append("---\n")
        md.append("## Conversation\n")
        
        # Messages
        for i, msg in enumerate(conversation, 1):
            role = msg.get('role', 'unknown')
            content = msg.get('content', '')
            
            if role == 'user':
                md.append(f"### 👤 Question {i}\n")
            else:
                md.append(f"### 🤖 Answer {i}\n")
            
            md.append(content)
            md.append("")
        
        # Footer
        md.append("---")
        md.append("\n*Generated by PDF-crewai v2.0*")
        
        return '\n'.join(md)
    
    def export_to_json(self, conversation: List[Dict], document_info: Dict = None, 
                      metadata: Dict = None) -> str:
        """
        Export to JSON format (machine-readable)
        
        Returns:
            JSON string
        """
        export_data = {
            'export_info': {
                'timestamp': datetime.now().isoformat(),
                'version': '2.0.0',
                'format': 'json'
            },
            'document': document_info or {},
            'conversation': conversation,
            'metadata': metadata or {}
        }
        
        return json.dumps(export_data, indent=2, ensure_ascii=False)
    
    def export_to_html(self, conversation: List[Dict], document_info: Dict = None) -> str:
        """
        Export to HTML format with styling
        
        Returns:
            HTML string
        """
        html = []
        
        # HTML header with CSS
        html.append("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Research Assistant - Conversation Export</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
            color: #333;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 12px;
            margin-bottom: 20px;
        }
        .document-info {
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .message {
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 15px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .user-message {
            border-left: 4px solid #667eea;
        }
        .ai-message {
            border-left: 4px solid #764ba2;
        }
        .message-header {
            font-weight: bold;
            margin-bottom: 10px;
            color: #667eea;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            color: #666;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
""")
        
        # Header
        html.append("""
    <div class="header">
        <h1>🧬 PDF Research Assistant</h1>
        <p>Conversation Export</p>
        <p style="font-size: 0.9em; opacity: 0.9;">""" + 
        f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}" + 
        """</p>
    </div>
""")
        
        # Document info
        if document_info:
            html.append("""
    <div class="document-info">
        <h2>📄 Document Information</h2>
        <ul>
            <li><strong>Filename:</strong> """ + document_info.get('filename', 'Unknown') + """</li>
            <li><strong>Upload Date:</strong> """ + document_info.get('upload_date', 'Unknown') + """</li>
            <li><strong>Size:</strong> """ + f"{document_info.get('size_mb', 0):.2f} MB" + """</li>
        </ul>
    </div>
""")
        
        # Conversation
        html.append("""
    <h2>💬 Conversation</h2>
""")
        
        for i, msg in enumerate(conversation, 1):
            role = msg.get('role', 'unknown')
            content = msg.get('content', '').replace('\n', '<br>')
            
            if role == 'user':
                css_class = 'user-message'
                header = f'👤 Question {i}'
            else:
                css_class = 'ai-message'
                header = f'🤖 Answer {i}'
            
            html.append(f"""
    <div class="message {css_class}">
        <div class="message-header">{header}</div>
        <div>{content}</div>
    </div>
""")
        
        # Footer
        html.append("""
    <div class="footer">
        <p>Generated by PDF-crewai v2.0</p>
        <p>Powered by AI</p>
    </div>
</body>
</html>
""")
        
        return ''.join(html)
    
    def export_to_text(self, conversation: List[Dict], document_info: Dict = None) -> str:
        """
        Export to plain text format
        
        Returns:
            Plain text string
        """
        lines = []
        
        # Header
        lines.append("=" * 60)
        lines.append("PDF RESEARCH ASSISTANT - CONVERSATION EXPORT")
        lines.append("=" * 60)
        lines.append(f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        
        if document_info:
            lines.append("DOCUMENT INFORMATION")
            lines.append("-" * 60)
            lines.append(f"Filename: {document_info.get('filename', 'Unknown')}")
            lines.append(f"Upload Date: {document_info.get('upload_date', 'Unknown')}")
            lines.append(f"Size: {document_info.get('size_mb', 0):.2f} MB")
            lines.append("")
        
        lines.append("CONVERSATION")
        lines.append("=" * 60)
        lines.append("")
        
        # Messages
        for i, msg in enumerate(conversation, 1):
            role = msg.get('role', 'unknown')
            content = msg.get('content', '')
            
            if role == 'user':
                lines.append(f"[Question {i}]")
            else:
                lines.append(f"[Answer {i}]")
            
            lines.append(content)
            lines.append("")
            lines.append("-" * 60)
            lines.append("")
        
        # Footer
        lines.append("Generated by PDF-crewai v2.0")
        
        return '\n'.join(lines)
    
    def create_summary_report(self, conversation: List[Dict], document_info: Dict, 
                             analytics: Dict = None) -> str:
        """
        Create a comprehensive summary report
        
        Returns:
            Markdown formatted report
        """
        md = []
        
        md.append("# 📊 PDF Analysis Report\n")
        md.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        md.append("---\n")
        
        # Document Summary
        md.append("## 📄 Document Summary\n")
        md.append(f"**Filename:** {document_info.get('filename', 'Unknown')}")
        md.append(f"**Type:** {document_info.get('type', 'Unknown')}")
        md.append(f"**Size:** {document_info.get('size_mb', 0):.2f} MB")
        md.append(f"**Pages:** ~{document_info.get('pages_estimate', 'Unknown')}")
        md.append("")
        
        # Key Insights
        md.append("## 🔍 Key Insights\n")
        
        # Extract questions and answers
        questions = [msg['content'] for msg in conversation if msg.get('role') == 'user']
        
        md.append(f"**Total Questions Asked:** {len(questions)}")
        md.append("")
        
        if questions:
            md.append("**Topics Explored:**")
            for i, q in enumerate(questions[:5], 1):
                md.append(f"{i}. {q[:100]}...")
            md.append("")
        
        # Analytics
        if analytics:
            md.append("## 📈 Session Analytics\n")
            md.append(f"**Session Duration:** {analytics.get('duration', 'Unknown')}")
            md.append(f"**Tokens Used:** {analytics.get('tokens_used', 'Unknown')}")
            md.append(f"**Provider:** {analytics.get('provider', 'Unknown')}")
            md.append("")
        
        # Full Conversation
        md.append("## 💬 Full Conversation\n")
        
        for i, msg in enumerate(conversation, 1):
            role = msg.get('role', 'unknown')
            content = msg.get('content', '')
            
            if role == 'user':
                md.append(f"### Q{i}: {content}\n")
            else:
                md.append(f"**A{i}:**\n{content}\n")
        
        md.append("---")
        md.append("\n*Report generated by PDF-crewai v2.0*")
        
        return '\n'.join(md)
